### ISSUE TITLE
Cancel and send buttons on feedback form do not work

### ISSUE THREAD

**Issue by johannesschweig** [mrzmyr/pixy-mood-tracker-app#14]
I tried to use the feedback form, but neither the cancel nor the send button did anything. The rest of the UI (selection Issue, Idea, Other, textfields) were functional. I could go back with the phone's back button.

Phone: OnePlus Nord
Android: 12

**Comment by mrzmyr** [comment]
Hey @johannesschweig, just tested it and I can confirm the behavior you're describing. Will be fixed in the next version as of https://github.com/mrzmyr/pixy-mood-tracker-app/commit/c52f06ed4f23b19c381b933f93d4cf8a57ac3efc.
