### ISSUE TITLE
Issue with Importing Daylio Data to Pixy

### ISSUE THREAD

**Issue by c0pper** [mrzmyr/pixy-mood-tracker-app#208]
Description:
I attempted to import my data from the Daylio app to Pixy. First, I exported dummy data from the Pixy app, then I converted my Daylio data to the Pixy format with python. However, upon importing the converted data into Pixy, I encountered an issue where the app won't recognize it, regardless of what I try.

Interestingly, when I inserted one original Pixy item among the converted Daylio items, the app recognized it without any issues. However, the rest of the converted Daylio items did not get recognized by Pixy.

I have carefully reviewed the format and structure of both the converted Daylio items and the original Pixy items, but I couldn't identify any significant differences that could explain this issue.

I will attach the file containing the converted Daylio items that I'm trying to import. If possible, could someone from the support team try importing this file into Pixy to see if they encounter the same issue?

Thank you for your assistance in resolving this matter.
[dump.json](https://github.com/mrzmyr/pixy-mood-tracker-app/files/15286281/dump.json)

**Comment by mrzmyr** [comment]
@c0pper thank you so much for taking the time to put all this info together. I do not support the App anymore but eventually plan to do a Pixy 2 version in the future. If you're interested in providing feedback, feel free to join the discord here: https://discord.gg/4JpfBqyT
