### ISSUE TITLE
Check-in Menu cut off at top

### ISSUE THREAD

**Issue by chrisvrose** [mrzmyr/pixy-mood-tracker-app#212]
The top section of the check in menu is cut off, and I have no way to select "Mood".

Device: Samsung M34
Android version: 14
OneUI version: 6.1

![Screenshot_20240917_101715_Pixy](https://github.com/user-attachments/assets/6fc7c128-67f3-496e-8a3b-7e8b40181ef3)

- may be related to #162 

## Steps to reproduce

1. Open Settings tab
2. Click on onboarding
3. Go back (or run through all of the steps)
4. Click on check in

**Comment by mrzmyr** [comment]
Thanks for reporting! Sorry for the late reply. I do not support the App anymore but eventually plan to do a Pixy 2 version in the future. If you're interested in providing feedback, feel free to join the discord here: https://discord.gg/4JpfBqyT
