### ISSUE TITLE
Urgent: Android 15 dropped support for this app and it's no longer available!

### ISSUE THREAD

**Issue by mags0ft** [mrzmyr/pixy-mood-tracker-app#213]
Hello there,

I am really enjoying this app, but it can no longer be acquired from the Play Store; it does no longer work on Android 15. Installing it on Android 14 worked. You may need to raise the API level to get it working again, shouldn't be a too big step involving only running an update for the expo CLI and then executing expo upgrade.

Best regards! I hope the app becomes available soon again :)

**Comment by mrzmyr** [comment]
Hey @mags0ft, just got the email from Google Play Store as well. Unfortunately, I do not support this anymore. :/ I think the best options is to build the app locally and install the APK.

**Comment by mrzmyr** [comment]
I eventually plan to do a Pixy 2 version in the future. If you're interested in providing feedback, feel free to join the discord here: https://discord.gg/4JpfBqyT

**Comment by mags0ft** [comment]
It's absolutely okay, I fully understand! I already pondered about forking this amazing app either way... great work, man - let's see where it goes in the future :)
