### ISSUE TITLE
Import from "Pixels" and longer history

### ISSUE THREAD

**Issue by julianschelb** [mrzmyr/pixy-mood-tracker-app#214]
Hello 👋,

I was super happy to find this app and even happier to see that it has an import/export feature, as I wanted to migrate from the Pixels app to something better. Writing a conversion script was pretty easy! Here’s the repo if anyone is interested:
https://github.com/julianschelb/convert_pixels_to_pixy

Here’s my issue: I can’t figure out how to view data older than a year. The re-exported data includes everything back to 2020 (when I started logging), but I can’t find an option in the app to access data beyond the past year.

Is there something specific I need to pay attention to when importing more than a year of data? Or is it just not possible to go further back?

Thanks!

Julian

**Comment by mrzmyr** [comment]
Hey @julianschelb, it's simply not possible right now to go back later than a year. :) Sorry 🫶
