### ISSUE TITLE
Discord invite link is invalid

### ISSUE THREAD

**Issue by mags0ft** [mrzmyr/pixy-mood-tracker-app#216]
Hello there (again),

currently, it seems like the invite link for the Discord server inside of the README.md file is no longer working. This makes it harder for people who want to learn more about the future of Pixy to follow along. It'd be splendid if it could be updated! :)

Greets

**Comment by mrzmyr** [comment]
ty! Updated it :)

https://discord.gg/tt7KRRc3uF

never expires :)

**Comment by mags0ft** [comment]
Amazing, thanks!
